<a href="https://colab.research.google.com/github/Hygl0110/SelfDataLearnig/blob/normalize_vinilosDB/normalizacion_datos_vinilos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np



#tabla en formato ancho raw como se estaba trabajando hasta la fecha
df = pd.read_excel('datosRAW_01.xlsx')
#indexamos la tabla
df = df.reset_index().rename(columns={'index': 'fila_original'})

df

,fila_original,ID_produccion,Fecha,Maquina,Operario,Referencia,Pacas_producidas,Horas_trabajadas,Turno,Sub_Codigo_de_paro_1,...,Codigo_9_en_horas,Codigo_10_en_horas,Codigo_11_en_horas,Codigo_12_en_horas,Codigo_13_en_horas,Codigo_14_en_horas,Codigo_15_en_horas,Codigo_16_en_horas,Codigo_17_en_horas,Codigo_18_en_horas
0,0,20251023-43,2025-10-23,Vinilos_4,Natalia P.,Torre 22cc (12 col),49.0,9,9pm-6am (Turno 3),NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.083333,0.666667,0.05,0.0
1,1,20251023-43,2025-10-23,Vinilos_4,Natalia P.,Torre 22cc (12 col),NaN,NaN,9pm-6am (Turno 3),NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.00,0.0
2,2,20251023-42,2025-10-23,Vinilos_4,Monica,Torre 22cc (12 col),30.0,7.5,1:30pm-9pm (Turno 2),NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.666667,0.05,1.5
3,3,20251023-41,2025-10-23,Vinilos_4,Carla,Alocolor 22cc (12 col),30.0,7.5,6am-1:30pm (Turno 1),NaN,...,0.0,0.0,0.0,0.250000,0.0,0.5,0.083333,0.666667,0.05,0.0
4,4,20251024-43,2025-10-24,Vinilos_4,Marcela,Torre 22cc (12 col),39.0,9,9pm-6am (Turno 3),NaN,...,0.0,0.0,0.0,0.166667,0.0,0.0,0.166667,0.666667,0.05,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4945,4945,20240102-31,2024-01-02,Vinilos_3,Alexandra,Torre 22cc (6 col),NaN,NaN,6am-2pm (Turno 1),NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.00,0.0
4946,4946,20240101-2,2024-01-01,Vinilos_2,No aplica,NaN,0.0,0,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.00,0.0
4947,4947,20240101-4,2024-01-01,Vinilos_4,No aplica,NaN,0.0,0,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.00,0.0
4948,4948,20240101-3,2024-01-01,Vinilos_3,No aplica,NaN,0.0,0,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.00,0.0
4949,4949,20240101-1,2024-01-01,Vinilos_1,No aplica,NaN,0.0,0,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.00,0.0

In [2]:
#nombres de las columnas de la base de datos, para copiar y pegar en los arrays
df.columns.to_list()

['fila_original',
 'ID_produccion',
 'Fecha',
 'Maquina',
 'Operario',
 'Referencia',
 'Pacas_producidas',
 'Horas_trabajadas',
 'Turno',
 'Sub_Codigo_de_paro_1',
 'Codigo_1_en_horas',
 'Codigo_2_en_horas',
 'Subcodigo_3',
 'Codigo_3_en_horas',
 'Codigo_4_en_horas',
 'Subcodigo_5',
 'Codigo_5_en_horas',
 'Área_involucrada_en_subcodigo_5',
 'Codigo_6_en_horas',
 'Codigo_7_en_horas',
 'Codigo_8_en_horas',
 'Codigo_9_en_horas',
 'Codigo_10_en_horas',
 'Codigo_11_en_horas',
 'Codigo_12_en_horas',
 'Codigo_13_en_horas',
 'Codigo_14_en_horas',
 'Codigo_15_en_horas',
 'Codigo_16_en_horas',
 'Codigo_17_en_horas',
 'Codigo_18_en_horas']

In [3]:
# tabla de producción

#nombres de las columnas de produccion
cols_info = ['ID_produccion', 'Fecha', 'Maquina', 'Operario', 'Referencia', 'Turno']
#agrupamos las filas por id y sumamos los valores
df_produccion = df.groupby(cols_info, as_index=False)[['Pacas_producidas', 'Horas_trabajadas']].sum()

#ya que se presentan ID repetidos por errores humanos, vamos a tomar todos los ID repetidos y a sumar las columnas numericas
#y solo mantener la informacion de la primera fila que aparezca
df_produccion = (
    df_produccion.groupby('ID_produccion', as_index=False)
    .agg({
        'Fecha': 'first',
        'Maquina': 'first',
        'Turno': 'first',
        'Operario': 'first',
        'Referencia': 'first',
        'Pacas_producidas': 'sum',
        'Horas_trabajadas': 'sum'
    })
)

df_produccion.head()

,ID_produccion,Fecha,Maquina,Turno,Operario,Referencia,Pacas_producidas,Horas_trabajadas
0,20240102-11,2024-01-02,Vinilos_1,6am-2pm (Turno 1),Lorena T.,Pintorcitos 15cc (6 col),43.0,8
1,20240102-12,2024-01-02,Vinilos_1,2pm-10pm (Turno 2),Erika H.,Pintorcitos 15cc (6 col),40.0,8
2,20240102-13,2024-01-02,Vinilos_1,10pm-6am (Turno 3),Monica,Pintorcitos 15cc (6 col),41.0,8
3,20240102-2p,2024-01-02,Vinilos_2,6am-4:30pm,Helen,Parchesitos 125 cc,374.0,10.5
4,20240102-31,2024-01-02,Vinilos_3,6am-2pm (Turno 1),Alexandra,Torre 22cc (6 col),67.0,8

In [4]:
#extraccion unicamente de los nombres de las columnas que contengan codigo y en horas
cols_codigos = [c for c in df.columns if c.startswith("Codigo_") and c.endswith("_en_horas")]
cols_codigos

['Codigo_1_en_horas',
 'Codigo_2_en_horas',
 'Codigo_3_en_horas',
 'Codigo_4_en_horas',
 'Codigo_5_en_horas',
 'Codigo_6_en_horas',
 'Codigo_7_en_horas',
 'Codigo_8_en_horas',
 'Codigo_9_en_horas',
 'Codigo_10_en_horas',
 'Codigo_11_en_horas',
 'Codigo_12_en_horas',
 'Codigo_13_en_horas',
 'Codigo_14_en_horas',
 'Codigo_15_en_horas',
 'Codigo_16_en_horas',
 'Codigo_17_en_horas',
 'Codigo_18_en_horas']

In [5]:
#uso de melt para convertir las columnas en filas para generar una tabla, cada una es un posible paro por ID y numero de fila--> convertir en formato largo
df_paros = df.melt(
    id_vars=['fila_original', 'ID_produccion'],
    value_vars=[c for c in df.columns if c.startswith("Codigo_") and c.endswith("_en_horas")],
    var_name='Codigo_col',
    value_name='Tiempo_en_horas'
)
df_paros = df_paros.copy()
df_paros

       fila_original ID_produccion          Codigo_col  Tiempo_en_horas
0                  0   20251023-43   Codigo_1_en_horas              0.0
1                  1   20251023-43   Codigo_1_en_horas              0.0
2                  2   20251023-42   Codigo_1_en_horas              0.0
3                  3   20251023-41   Codigo_1_en_horas              0.0
4                  4   20251024-43   Codigo_1_en_horas              0.0
...              ...           ...                 ...              ...
89095           4945   20240102-31  Codigo_18_en_horas              0.0
89096           4946    20240101-2  Codigo_18_en_horas              0.0
89097           4947    20240101-4  Codigo_18_en_horas              0.0
89098           4948    20240101-3  Codigo_18_en_horas              0.0
89099           4949    20240101-1  Codigo_18_en_horas              0.0

[89100 rows x 4 columns]

In [6]:
#crear una nueva columnas y extraer unicamente el numero en el calor de codigo de paro del codigo de paro
df_paros['Codigo_de_paro'] = df_paros['Codigo_col'].str.extract(r'Codigo_(\d+)_').astype(int)
df_paros

,fila_original,ID_produccion,Codigo_col,Tiempo_en_horas,Codigo_de_paro
0,0,20251023-43,Codigo_1_en_horas,0.0,1
1,1,20251023-43,Codigo_1_en_horas,0.0,1
2,2,20251023-42,Codigo_1_en_horas,0.0,1
3,3,20251023-41,Codigo_1_en_horas,0.0,1
4,4,20251024-43,Codigo_1_en_horas,0.0,1
...,...,...,...,...,...
89095,4945,20240102-31,Codigo_18_en_horas,0.0,18
89096,4946,20240101-2,Codigo_18_en_horas,0.0,18
89097,4947,20240101-4,Codigo_18_en_horas,0.0,18
89098,4948,20240101-3,Codigo_18_en_horas,0.0,18
89099,4949,20240101-1,Codigo_18_en_horas,0.0,18

In [7]:
#matris de booleanos para tomar unicamente las filas con dato en tiempo de los paros
df_paros = df_paros[df_paros['Tiempo_en_horas'] > 0]
df_paros

,fila_original,ID_produccion,Codigo_col,Tiempo_en_horas,Codigo_de_paro
12,12,20251025-41,Codigo_1_en_horas,0.166667,1
32,32,20251010-43,Codigo_1_en_horas,0.416667,1
33,33,20251010-43,Codigo_1_en_horas,0.250000,1
34,34,20251010-43,Codigo_1_en_horas,0.666667,1
42,42,20251006-41,Codigo_1_en_horas,0.166667,1
...,...,...,...,...,...
85892,1742,20250114-11,Codigo_18_en_horas,0.333333,18
85905,1755,20250113-11,Codigo_18_en_horas,0.533333,18
85964,1814,20250103-21,Codigo_18_en_horas,1.000000,18
86036,1886,20241223-42,Codigo_18_en_horas,0.500000,18
86069,1919,20241219-43,Codigo_18_en_horas,1.000000,18

In [8]:
#tabla auxiliar con la informacio de los subcodigos de paro y areas de codigo 5
# 2. Creamos tabla auxiliar con subcodigos y área
df_subinfo = df[['fila_original','Sub_Codigo_de_paro_1','Subcodigo_3','Subcodigo_5','Área_involucrada_en_subcodigo_5']]

In [9]:
#merge de tabla paros con tabla auxiliar por el numero de fila
df_paros = df_paros.merge(df_subinfo, on='fila_original', how='left')
df_paros

,fila_original,ID_produccion,Codigo_col,Tiempo_en_horas,Codigo_de_paro,Sub_Codigo_de_paro_1,Subcodigo_3,Subcodigo_5,Área_involucrada_en_subcodigo_5
0,12,20251025-41,Codigo_1_en_horas,0.166667,1,1.2.A Cambio de racores,NaN,5.11 Lavado de boquilla,NaN
1,32,20251010-43,Codigo_1_en_horas,0.416667,1,1.2.C Cambio de Valvula,NaN,"5.2 Sistema de dosificación de pintura, fronta...",NaN
2,33,20251010-43,Codigo_1_en_horas,0.250000,1,1.2.A Cambio de racores,NaN,NaN,NaN
3,34,20251010-43,Codigo_1_en_horas,0.666667,1,1.2.C Cambio de Valvula,NaN,5.11 Lavado de boquilla,NaN
4,42,20251006-41,Codigo_1_en_horas,0.166667,1,1.1.C Sensor,NaN,5.11 Lavado de boquilla,NaN
...,...,...,...,...,...,...,...,...,...
13261,1742,20250114-11,Codigo_18_en_horas,0.333333,18,NaN,NaN,5.9 Sistema de etiquetado,Operarios
13262,1755,20250113-11,Codigo_18_en_horas,0.533333,18,NaN,NaN,Sin especificar,Operarios
13263,1814,20250103-21,Codigo_18_en_horas,1.000000,18,NaN,NaN,NaN,NaN
13264,1886,20241223-42,Codigo_18_en_horas,0.500000,18,NaN,NaN,"5.2 Sistema de dosificación de pintura, fronta...",Personal_de_mantenimiento
13265,1919,20241219-43,Codigo_18_en_horas,1.000000,18,NaN,NaN,"5.2 Sistema de dosificación de pintura, fronta...",Operarios

In [10]:
#insertar columnas vacias para luego rellenar con los datos de subcodigo y area
df_paros['Subcodigo'] = None
df_paros['Area_involucrada'] = None
df_paros

,fila_original,ID_produccion,Codigo_col,Tiempo_en_horas,Codigo_de_paro,Sub_Codigo_de_paro_1,Subcodigo_3,Subcodigo_5,Área_involucrada_en_subcodigo_5,Subcodigo,Area_involucrada
0,12,20251025-41,Codigo_1_en_horas,0.166667,1,1.2.A Cambio de racores,NaN,5.11 Lavado de boquilla,NaN,None,None
1,32,20251010-43,Codigo_1_en_horas,0.416667,1,1.2.C Cambio de Valvula,NaN,"5.2 Sistema de dosificación de pintura, fronta...",NaN,None,None
2,33,20251010-43,Codigo_1_en_horas,0.250000,1,1.2.A Cambio de racores,NaN,NaN,NaN,None,None
3,34,20251010-43,Codigo_1_en_horas,0.666667,1,1.2.C Cambio de Valvula,NaN,5.11 Lavado de boquilla,NaN,None,None
4,42,20251006-41,Codigo_1_en_horas,0.166667,1,1.1.C Sensor,NaN,5.11 Lavado de boquilla,NaN,None,None
...,...,...,...,...,...,...,...,...,...,...,...
13261,1742,20250114-11,Codigo_18_en_horas,0.333333,18,NaN,NaN,5.9 Sistema de etiquetado,Operarios,None,None
13262,1755,20250113-11,Codigo_18_en_horas,0.533333,18,NaN,NaN,Sin especificar,Operarios,None,None
13263,1814,20250103-21,Codigo_18_en_horas,1.000000,18,NaN,NaN,NaN,NaN,None,None
13264,1886,20241223-42,Codigo_18_en_horas,0.500000,18,NaN,NaN,"5.2 Sistema de dosificación de pintura, fronta...",Personal_de_mantenimiento,None,None
13265,1919,20241219-43,Codigo_18_en_horas,1.000000,18,NaN,NaN,"5.2 Sistema de dosificación de pintura, fronta...",Operarios,None,None

In [11]:
#rellenamos los datos de subcodigo y merge pare mantener la integridad de los datos
df_paros.loc[df_paros['Codigo_de_paro'] == 1, 'Subcodigo'] = df_paros['Sub_Codigo_de_paro_1']
df_paros.loc[df_paros['Codigo_de_paro'] == 3, 'Subcodigo'] = df_paros['Subcodigo_3']
df_paros.loc[df_paros['Codigo_de_paro'] == 5, 'Subcodigo'] = df_paros['Subcodigo_5']

#rellenar los datos de area involucrada
df_paros.loc[df_paros['Codigo_de_paro'] == 5, 'Area_involucrada'] = df_paros['Área_involucrada_en_subcodigo_5']

df_paros

,fila_original,ID_produccion,Codigo_col,Tiempo_en_horas,Codigo_de_paro,Sub_Codigo_de_paro_1,Subcodigo_3,Subcodigo_5,Área_involucrada_en_subcodigo_5,Subcodigo,Area_involucrada
0,12,20251025-41,Codigo_1_en_horas,0.166667,1,1.2.A Cambio de racores,NaN,5.11 Lavado de boquilla,NaN,1.2.A Cambio de racores,None
1,32,20251010-43,Codigo_1_en_horas,0.416667,1,1.2.C Cambio de Valvula,NaN,"5.2 Sistema de dosificación de pintura, fronta...",NaN,1.2.C Cambio de Valvula,None
2,33,20251010-43,Codigo_1_en_horas,0.250000,1,1.2.A Cambio de racores,NaN,NaN,NaN,1.2.A Cambio de racores,None
3,34,20251010-43,Codigo_1_en_horas,0.666667,1,1.2.C Cambio de Valvula,NaN,5.11 Lavado de boquilla,NaN,1.2.C Cambio de Valvula,None
4,42,20251006-41,Codigo_1_en_horas,0.166667,1,1.1.C Sensor,NaN,5.11 Lavado de boquilla,NaN,1.1.C Sensor,None
...,...,...,...,...,...,...,...,...,...,...,...
13261,1742,20250114-11,Codigo_18_en_horas,0.333333,18,NaN,NaN,5.9 Sistema de etiquetado,Operarios,None,None
13262,1755,20250113-11,Codigo_18_en_horas,0.533333,18,NaN,NaN,Sin especificar,Operarios,None,None
13263,1814,20250103-21,Codigo_18_en_horas,1.000000,18,NaN,NaN,NaN,NaN,None,None
13264,1886,20241223-42,Codigo_18_en_horas,0.500000,18,NaN,NaN,"5.2 Sistema de dosificación de pintura, fronta...",Personal_de_mantenimiento,None,None
13265,1919,20241219-43,Codigo_18_en_horas,1.000000,18,NaN,NaN,"5.2 Sistema de dosificación de pintura, fronta...",Operarios,None,None

In [12]:
#conservar unicamente las columnas de interes y organizar
df_paros = df_paros[['ID_produccion', 'Codigo_de_paro', 'Subcodigo', 'Area_involucrada', 'Tiempo_en_horas']]
df_paros

,ID_produccion,Codigo_de_paro,Subcodigo,Area_involucrada,Tiempo_en_horas
0,20251025-41,1,1.2.A Cambio de racores,None,0.166667
1,20251010-43,1,1.2.C Cambio de Valvula,None,0.416667
2,20251010-43,1,1.2.A Cambio de racores,None,0.250000
3,20251010-43,1,1.2.C Cambio de Valvula,None,0.666667
4,20251006-41,1,1.1.C Sensor,None,0.166667
...,...,...,...,...,...
13261,20250114-11,18,None,None,0.333333
13262,20250113-11,18,None,None,0.533333
13263,20250103-21,18,None,None,1.000000
13264,20241223-42,18,None,None,0.500000
13265,20241219-43,18,None,None,1.000000

In [13]:
#extrear ambas tablas en formato excel para su uso interno
df_produccion.to_excel("produccion_procesada.xlsx", index=False)
df_paros.to_excel("paros_procesados.xlsx", index=False)